version: '3.3'

services:
  frontend:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - /mnt/frontend/oph_frontend:/usr/share/nginx/html
    depends_on:
      - api
      - mariadb

  api:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - /mnt/api/oph_api:/usr/src/app
    command: sh -c "npm install && npm run start"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mariadb
    networks:
      - oph_network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: buopen@dm1n2024
      MYSQL_DATABASE: oph
      MYSQL_USER: oph
      MYSQL_PASSWORD: buopen@dm1n2024
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - oph_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: buopen@dm1n2024
    depends_on:
      - mariadb
    networks:
      - oph_network

volumes:
  mariadb_data:

networks:
  oph_network:
    driver: bridge